export const THEME_KEY = [
  {
    label: '생일',
    title: '생일 축하해! 🎉',
    description: '특별한 날을 더욱 특별하게 만들어 줄 선물',
    color: '#FFD1DC',
    themeKey: 'birthday',
  },
  {
    label: '졸업선물',
    title: '졸업을 축하합니다! 🎓',
    description: '새로운 시작을 응원하는 특별한 선물',
    color: '#FFB347',
    themeKey: 'graduation',
  },
  {
    label: '스몰럭셔리',
    title: '작지만 럭셔리한 선물 ✨',
    description: '작은 사치로 일상을 더욱 특별하게',
    color: '#B39EB5',
    themeKey: 'small-luxury',
  },
  {
    label: '명품선물',
    title: '명품의 가치 💎',
    description: '특별한 사람에게 전하는 고급스러운 선물',
    color: '#AEC6CF',
    themeKey: 'luxury',
  },
  {
    label: '결혼/집들이',
    title: '행복한 시작을 함께 🎊',
    description: '결혼과 새로운 집을 위한 따뜻한 선물',
    color: '#FF6961',
    themeKey: 'wedding-housewarming',
  },
  {
    label: '따뜻한 선물',
    title: '마음을 전하는 따뜻한 선물 💖',
    description: '추운 날씨에도 마음을 따뜻하게 해줄 선물',
    color: '#FDFD96',
    themeKey: 'warm-gifts',
  },
  {
    label: '가벼운선물',
    title: '예산은 가볍게, 감동은 무겁게 ❤️',
    description: '당신의 센스를 뽐내줄 부담 없는 선물',
    color: '#77DD77',
    themeKey: 'light-gifts',
  },
  {
    label: '팬심저격',
    title: '팬심을 저격하는 선물 🎁',
    description: '팬심을 담아 전하는 특별한 선물',
    color: '#CFCFC4',
    themeKey: 'fan-favorite',
  },
  {
    label: '교환권',
    title: '유용한 교환권 🎟️',
    description: '실용적이고 편리한 다양한 교환권 선물',
    color: '#779ECB',
    themeKey: 'exchange-tickets',
  },
  {
    label: '건강/비타민',
    title: '건강을 챙기는 선물 🍏',
    description: '건강과 활력을 위한 비타민과 건강식품 선물',
    color: '#C3B091',
    themeKey: 'health-vitamins',
  },
  {
    label: '과일/한우',
    title: '신선한 과일과 한우 🥩',
    description: '건강하고 맛있는 과일과 한우 선물',
    color: '#F49AC2',
    themeKey: 'fruits-beef',
  },
  {
    label: '출산/키즈',
    title: '출산과 키즈를 위한 선물 👶',
    description: '새로운 생명과 아이들을 위한 특별한 선물',
    color: '#B19CD9',
    themeKey: 'birth-kids',
  },
];
