import GiftImg from '@/assets/main/Item_Icon.jpeg';

export const TypeData = [
  {
    title: '생일',
    type: 'birthday-gift',
    mainTitle: '감동을 높여줄 생일 선물 리스트',
    subTitle: '생일 선물로 누군가에게 특별한 감동을 선사해보세요.',
    backgroundColor: '#5849a3',
    image: GiftImg,
  },
  {
    title: '졸업선물',
    type: 'graduation-gift',
    mainTitle: '졸업을 축하하는 선물 리스트',
    subTitle: '졸업을 축하하는 마음을 선물로 전달해보세요.',
    backgroundColor: '#45604d',
    image: GiftImg,
  },
  {
    title: '스몰럭셔리',
    type: 'small-luxury-gift',
    mainTitle: '스몰럭셔리 선물 리스트',
    subTitle: '작지만 큰 감동을 선물해보세요.',
    backgroundColor: '#765240',
    image: GiftImg,
  },
  {
    title: '명품선물',
    type: 'luxury-gift',
    mainTitle: '명품 선물 리스트',
    subTitle: '특별한 사람에게 특별한 선물을 선물해보세요.',
    backgroundColor: '#515c7a',
    image: GiftImg,
  },
  {
    title: '결혼/집들이',
    type: 'wedding-gift',
    mainTitle: '결혼/집들이 선물 리스트',
    subTitle: '결혼식이나 집들이 선물로 좋은 선물을 찾아보세요.',
    backgroundColor: '#94785d',
    image: GiftImg,
  },
  {
    title: '따뜻한선물',
    type: 'life-warm-gift',
    mainTitle: '따뜻한 선물 리스트',
    subTitle: '따뜻한 마음을 전달하는 선물을 찾아보세요.',
    backgroundColor: 'rgb(187, 58, 58)',
    image: GiftImg,
  },
  {
    title: '가벼운선물',
    type: 'life-small-gift',
    mainTitle: '가벼운 선물 리스트',
    subTitle: '가벼운 마음을 전달하는 선물을 찾아보세요.',
    backgroundColor: '#4a4d50',
    image: GiftImg,
  },
  {
    title: '팬심저격',
    type: 'fan-gift',
    mainTitle: '팬심을 저격하는 선물 리스트',
    subTitle: '팬심을 저격하는 선물을 찾아보세요.',
    backgroundColor: '#212121',
    image: GiftImg,
  },
  {
    title: '교환권',
    type: 'coupon-gift',
    mainTitle: '교환권 선물 리스트',
    subTitle: '교환권을 선물로 전달해보세요.',
    backgroundColor: '#b2dfff',
    image: GiftImg,
  },
  {
    title: '건강/비타민',
    type: 'health-gift',
    mainTitle: '건강/비타민 선물 리스트',
    subTitle: '건강을 위한 선물을 찾아보세요.',
    backgroundColor: '#fc8197',
    image: GiftImg,
  },
  {
    title: '과일/한우',
    type: 'food-gift',
    mainTitle: '과일/한우 선물 리스트',
    subTitle: '맛있는 선물을 찾아보세요.',
    backgroundColor: '#ed6d59',
    image: GiftImg,
  },
  {
    title: '출산/키즈',
    type: 'kids-gift',
    mainTitle: '출산/키즈 선물 리스트',
    subTitle: '출산 및 아이들을 위한 선물을 찾아보세요.',
    backgroundColor: '#fc8197',
    image: GiftImg,
  },
];
