import menuImg from '@/assets/main/Gift_Icon.jpg';

export const targetData = [
  {
    buttonTitle: 'ALL',
    title: '전체',
  },
  {
    buttonTitle: '👩🏻‍🦳',
    title: '여성이',
  },
  {
    buttonTitle: '👨🏻‍🦳',
    title: '남성이',
  },
  {
    buttonTitle: '👦🏻',
    title: '청소년이',
  },
];

export const giftTypeData = [
  {
    type: '받고 싶어한',
  },
  {
    type: '많이 선물한',
  },
  {
    type: '위시로 받은',
  },
];

export const rankData = [
  {
    rank: 1,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '여성이',
    giftType: '많이 선물한',
  },
  {
    rank: 2,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '남성이',
    giftType: '받고 싶어한',
  },
  {
    rank: 3,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '청소년이',
    giftType: '위시로 받은',
  },
  {
    rank: 4,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '여성이',
    giftType: '받고 싶어한',
  },
  {
    rank: 5,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '남성이',
    giftType: '위시로 받은',
  },
  {
    rank: 6,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '청소년이',
    giftType: '많이 선물한',
  },
  {
    rank: 7,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '여성이',
    giftType: '위시로 받은',
  },
  {
    rank: 8,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '남성이',
    giftType: '많이 선물한',
  },
  {
    rank: 9,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '청소년이',
    giftType: '받고 싶어한',
  },
  {
    rank: 10,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '여성이',
    giftType: '받고 싶어한',
  },
  {
    rank: 11,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '남성이',
    giftType: '위시로 받은',
  },
  {
    rank: 12,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '청소년이',
    giftType: '많이 선물한',
  },
  {
    rank: 13,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '여성이',
    giftType: '받고 싶어한',
  },
  {
    rank: 14,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '남성이',
    giftType: '많이 선물한',
  },
  {
    rank: 15,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '청소년이',
    giftType: '위시로 받은',
  },
  {
    rank: 16,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '여성이',
    giftType: '많이 선물한',
  },
  {
    rank: 17,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '남성이',
    giftType: '받고 싶어한',
  },
  {
    rank: 18,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '청소년이',
    giftType: '위시로 받은',
  },
  {
    rank: 19,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '여성이',
    giftType: '받고 싶어한',
  },
  {
    rank: 20,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '남성이',
    giftType: '많이 선물한',
  },
  {
    rank: 21,
    Img: menuImg,
    storeTitle: 'BBQ',
    menu: 'BBQ 양념치킨+크림치즈볼+콜라1.25L',
    price: '29,000원',
    target: '청소년이',
    giftType: '위시로 받은',
  },
];
