const initialProducts = [
  { id: 1, category: '남성이', detail: '많이 선물한', name: 'Product 1' },
  { id: 2, category: '청소년이', detail: '많이 선물한', name: 'Product 2' },
  { id: 3, category: '남성이', detail: '위시로 받은', name: 'Product 3' },
  { id: 4, category: '여성이', detail: '받고 싶어한', name: 'Product 4' },
  { id: 5, category: '여성이', detail: '많이 선물한', name: 'Product 5' },
  { id: 6, category: '남성이', detail: '위시로 받은', name: 'Product 6' },
  { id: 7, category: '여성이', detail: '받고 싶어한', name: 'Product 7' },
  { id: 8, category: '청소년이', detail: '받고 싶어한', name: 'Product 8' },
  { id: 9, category: '남성이', detail: '위시로 받은', name: 'Product 9' },
  { id: 10, category: '여성이', detail: '많이 선물한', name: 'Product 10' },
  { id: 11, category: '청소년이', detail: '받고 싶어한', name: 'Product 11' },
  { id: 12, category: '청소년이', detail: '많이 선물한', name: 'Product 12' },
  { id: 13, category: '남성이', detail: '받고 싶어한', name: 'Product 13' },
  { id: 14, category: '여성이', detail: '많이 선물한', name: 'Product 14' },
  { id: 15, category: '청소년이', detail: '위시로 받은', name: 'Product 15' },
  { id: 16, category: '여성이', detail: '위시로 받은', name: 'Product 16' },
  { id: 17, category: '남성이', detail: '많이 선물한', name: 'Product 17' },
  { id: 18, category: '청소년이', detail: '받고 싶어한', name: 'Product 18' },
  { id: 19, category: '남성이', detail: '위시로 받은', name: 'Product 19' },
  { id: 20, category: '여성이', detail: '받고 싶어한', name: 'Product 20' },
  { id: 21, category: '청소년이', detail: '많이 선물한', name: 'Product 21' },
  { id: 22, category: '남성이', detail: '받고 싶어한', name: 'Product 22' },
  { id: 23, category: '여성이', detail: '많이 선물한', name: 'Product 23' },
  { id: 24, category: '남성이', detail: '위시로 받은', name: 'Product 24' },
  { id: 25, category: '여성이', detail: '받고 싶어한', name: 'Product 25' },
  { id: 26, category: '청소년이', detail: '위시로 받은', name: 'Product 26' },
  { id: 27, category: '남성이', detail: '많이 선물한', name: 'Product 27' },
  { id: 28, category: '여성이', detail: '많이 선물한', name: 'Product 28' },
  { id: 29, category: '청소년이', detail: '위시로 받은', name: 'Product 29' },
  { id: 30, category: '남성이', detail: '받고 싶어한', name: 'Product 30' },
];

export default initialProducts;
